language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
jobs:
    include:
        - name: "Python on Linux"
        - name: "Python on macOS
          os: osx
          language: shell     # 'language: python' is an error on Travis CI macOS
        - name: "Python on Windows"
          os: windows         # Windows 10.0.17134 N/A Build 17134
          language: shell     # 'language: python' is an error on Travis CI Windows
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - pytest --cov
after_success:
    - coveralls